### ISSUE TITLE
Soft delete should be refactored to be more consistent across find/delete operations on objects

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1035]
After the introduction of soft delete in #1027 we need to refactor that to better handle the operations on objects.

We could use a behavior with the aim of:

* intercept delete using `beforeDelete()` and save `deleted = 0` instead of really deleting objects
* intercept find using `beforeFind()` to setting `deleted = 0` conditions on every find query
* add custom finders to semplify some operations like `findTrashed()`, `deleteTrashed()` or similar

**Comment by fquffio** [comment]
I don't quite like the idea of intercepting an event and doing something nasty in place of what `$Table->delete()` is supposed to do. It sounds like something that might be counter-intuitive at times, something we could regret some day.

I'd rather add a new `$Table->softDelete()` method to do exactly this, and make Controller aware of whether it is a soft or hard delete that should be performed. Or we could overwrite `Table::delete()` method to allow for a `'soft' => true` flag in [`$options`](http://api.cakephp.org/3.3/class-Cake.ORM.Table.html#_delete).

In the same fashion, I'd prefer not to have some evil sorcerer add its conditions on every `SELECT` query, but rather add an eloquent `findStatus()` custom finder that can be used to `$Table->find('status', ['status' => ['on', 'draft'], 'deleted' => false])` every time we actually need it. Otherwise we might end up building awful hacks to work around some magic we put in place just to save a couple of lines of code elsewhere. 😉 

Apart from that, I think that instead of a Behavior, soft delete logic would better fit in a Trait.

**Comment by fquffio** [comment]
BTW, if `$Table->find('status', ['status' => ['on', 'draft'], 'deleted' => false])` looks too much verbose, we could add a method to Controller itself in order to modify a Query object by adding all conditions that are needed.

`Controller::paginate()` (that internally invokes `PaginatorComponent::paginate()`) does basically this in order to add pagination to virtually any query.

**Comment by batopa** [comment]
I agree that using a trait is better than behavior if we decide to not use `beforeDelete` and `beforeFind` events. 

We could implement explicit `softDelete()` method but for find method I don't know. 
I think is more clear to have `find()` method that get just not trashed objects because I expect that objects in the trash should never be visibles unless otherwise stated.

**Comment by stefanorosanelli** [comment]
``softDelete()`` method seems a good solution for me too

I agree with @batopa: I would expect that normal `find()` methods don't load deleted objects. Instead some parameters should be required to load deleted objects

**Comment by didoda** [comment]
obsolete
