### ISSUE TITLE
Delete fails if content type header is missing

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#1184]
Trying to delete an object through an API call with `DELETE` method to the url `/{type}/{id}`, I get a fail response with 500 code status and message: `Invalid header value; must be a string or array of strings`. Following the trace, I found out that it refers to the `Content-type` header.

**Comment by stefanorosanelli** [comment]
A `500` failure is obviously not the right response...
`Content-type` header on a `DELETE /{type}/{id}` should probably be ignored, and is not meaningful

I would suggest:
 * `Content-type` header should be missing in DELETE - this should be clear in the docs
 * we could ignore existing  `Content-type` header or we should respond with a `415 Unsupported Media Type` in case of bad content type


@batopa @fquffio @didoda

**Comment by fquffio** [comment]
The issue is caused by the controller trying to set the response's Content-Type using the same value as the request — if it's an empty string, this raises an error.

This issue could be easily circumvented by _not_ setting a Content-Type in a response that has no content. 🙃  However, per [JSON API spec](http://jsonapi.org/format/#crud-deleting) seems quite clear that the header Content-Type is not required in the request (in the example, only Accept header is present), whereas is not clear (at least to me) whether it is required in the response, if the response status is 204.

**Comment by stefanorosanelli** [comment]
Quick test: 
 * problem arises on missing or empty `Content-type` header
 * instead response is 204 on any value of `Conten-type` also putting random strings...
