### ISSUE TITLE
Custom email themes and templates using profiles 

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1242]
In `UserMailer` class and future mailer  we need to be able to use custom themes/templates defined in plugins.
This could be achieved with custom `profiles` associated to mailer actions - see https://book.cakephp.org/3.0/en/core-libraries/email.html#configuration-profiles

**Comment by fquffio** [comment]
I have done a simple test. Assuming there is a plugin named "MyPlugin":

```php
<?php
// in `config/app.php`
return [
    // ...
    'Email' => [
        'default' => [
            'transport' => 'default',
            'from' => 'me@example.org',
            'theme' => 'MyPlugin',
        ],
    ],
];
```

Then, add the following files:
- `plugins/MyPlugin/src/Template/Layout/Email/html/default.ctp`: HTML layout
- `plugins/MyPlugin/src/Template/Layout/Email/text/default.ctp`: text layout
- `plugins/MyPlugin/src/Template/Plugin/BEdita/Core/Email/html/signup.ctp`: HTML signup email template
- `plugins/MyPlugin/src/Template/Plugin/BEdita/Core/Email/text/signup.ctp`: text signup email template

Without any further change, the signup email is sent using the expected layout and template.

I think we can close this issue, since it's only matter of providing the correct configuration, and things will already work as expected.

**Comment by stefanorosanelli** [comment]
Good!
Closing...
