### ISSUE TITLE
Inheritance in custom properties

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1345]
As described in https://github.com/bedita/bedita/pull/1343#pullrequestreview-60596659 currently a object type that extends another type inherit custom properties.

For example given `users` extension of `profiles` extension of `objects` we can define a property on `profiles` type and save it via `users`.

```php
$users = TableRegistry::get('Users');
$u = $users->newEntity([
    'username' => 'xxx',
    'password' => 'yyy',
    'profiles_property' => 'property defined in profiles type',
]);
$users->save($u);
```

In `objects.custom_props` we'll have `profiles_property` also if it's not directly associated to users object type.

Is that the expected behavior or we should isolate custom properties by object type?

**Comment by stefanorosanelli** [comment]
What's the expected behavior is debatable, but if a **subtype** is  expected to inherit all its **parent type** properties it should also inherit also its `custom` properties.

Calling them `custom` is just an internal convention, those properties will appear to users and developers just like any other `core` properties, they might not be aware of the difference between `core` and `custom`.

**Comment by stefanorosanelli** [comment]
see also #908

**Comment by fquffio** [comment]
I agree with @stefanorosanelli: extending object types should work in a straightforward manner, and properties (and relationships) inheritance is something I would totally expect when "extending" something.
