### ISSUE TITLE
dynamic callbacks on backend operation

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#470]
We need a simple callback system (through dynamic addon components ??) to implement custom checks/controls/actions on specific backen operation like: save, create new or delete object.

**Comment by fquffio** [comment]
Following the path of what suggested by @batopa I added:
- a `BeCallbackManager`, that aims to be a basic event manager: one can bind/unbind listeners to an event, and trigger that event. Listeners can be either closures or arrays containing a class name (as aliased in `ClassRegistry`) and a method name. When triggering an event, an array of data can be associated to that event. For compatibility reasons, that data will be passed to the listener as arguments list, as well as the "event" object itself (last argument), so that we can set `$event->stopped = true` to stop its propagation or so. Everything returned by the listener will be put as the event result: multiple listeners will override their results, unless they take care of what's stored in `$event->result`.
- a `CallbackBehavior` that "translates" Cake's callbacks into events and correctly handles event results. Also, if attached to a model `MyModel`, it will search for any `MyModelWhateverBehavior` that will be attached to the model itself (either in Cake's way or binding its methods as listeners using `BeCallbackManager`, according to the `callbackManager` behavior setting).

## An example ##
Let's say we have a `Document` model (`CallbackBehavior` attached to it) and we enable the following addon behavior (not attaching it to Document model explicitely):
```php
<?php  // File: addons/models/behaviors/enabled/document_do_something.php
DocumentDoSomethingBehavior extends ModelBehavior {
    public function beforeSave ($model, &$event = null) {
        // $event should default to null, as it will be passed only if called within BeCallbackManager!
        if (!is_null($event)) {
            $event->stopped = true;
        }
        return false;  // Prevent all saves!
    }
    public function afterFind() {
        return array();  // Empty all find searches!
    }
}
```
If `CallbackBehavior` was configured to disable the use of `BeCallbackManager`, the behavior above will be just attached to Document and act as any other Behavior. If `BeCallbackManager` is used, this will act as a Behavior, with the added value of allowing us to gain much finer control, as we might call `BeLib::getObject('BeCallbackManager')->unbind('Document.afterFind')` to clear listeners for that event, thus removing the callback that empties all find searches.

## Inline callbacks ##
We can also quick-bind callbacks for some events, if needed, for example in a controller context, without having to create a behavior:
```php
BeLib::getObject('BeCallbackManager')->bind('Document.beforeFind', function ($model, $query) {
    pr($query);  // Debug!
});
```

@stefanorosanelli @batopa Suggestions? Critics? If that's alright to you, could you please help me with tests?

**Comment by stefanorosanelli** [comment]
Ok, if I understand we could add `CallbackBehavior` in model definitions to enable the automatic callback behavior discovery and setup and use `BeCallbackManager` to bind/unbind specific listeners.
Seems ok, will do some testing.
I assume the workflow would be:
 * activate new custom behavior `MyModelWhateverBehavior` - in addons or in any plugin module?
 * BEdita cleanup
 * from first use new behaviors are automatically added

@batopa @fquffio do we have to add `CallbackBehavior` to all main BEdita models?
Are there any potential performance issues with that ?

**Comment by fquffio** [comment]
@stefanorosanelli As of c63a583 `CallbackBehavior` has already been attached to `BeAppObjectModel`, so every BE Object model event is already bindable this way.

Behaviors are fetched from every possibile location, meaning plugged modules, addons, frontends, ...

I did some basic performance tests, and as this feature uses only built-in Cake methods to find out which available behavior names match the pattern, it seem to have a very little overhead cost, meaning that it could be left enabled by default.
Anyway, it should be easy to add a configuration switch to completely enable/disable this callback functionality.

**Comment by stefanorosanelli** [comment]
Thanks, did a simple text creating behaviors inside a plugin module and it works.
Good job!

**Comment by stefanorosanelli** [comment]
Having a configuration switch is a good idea, keep it in mind for now, we will implement it only in case of real performance issues.

**Comment by batopa** [comment]
I'm doing some simple test.
I receive a Fatal Error in `beforeFind()` and `afterFind()` after cleanup cache. After that all seems to work properly.

I have a simple Behavior in `addons/models/behaviors/enabled/document_test_behavior.php`.

```php
class DocumentTestBehavior extends ModelBehavior {

    public function beforeFind(&$model, $query, $event = null) {
        $this->log('beforeFind', 'debug');
        return true;
    }

    public function afterFind(&$model, $results, $primary, $event = null) {
        $this->log('afterFind', 'debug');
    }

}
```

doing

```bash
$ ./cake.sh bedita cleanup
```

and loading a document I have

```
Notice (8): Undefined property: CallbackBehavior::$manager [APP/models/behaviors/callback.php, line 146]
Fatal error: Call to a member function trigger() on a non-object in /home/bato/ws/github/bedita/bedita-app/models/behaviors/callback.php on line 146
```

Then reloading the page it all works and I see the message in `debug.log`

**Comment by fquffio** [comment]
@batopa Committed a fix for that issue, as well as a minor performance improvement when loading behaviors list.

**Comment by batopa** [comment]
@fquffio ok, I'll try to test as soon as possible

Talking with @stefanorosanelli we have though it is better to change the name of behaviors that are automagically hooked to avoid unwanted behaviors are connected.

`DocumentWhateverBehavior` becomes `DocumentWhateverCallbackBehavior`.

In this way we define that the behavior is intended to use through `CallbackBehavior`

**Comment by stefanorosanelli** [comment]
Bug in previous comment from @batopa is now solved.

New convention `ModelNameSomethingCallbackBehavior` is ok

Last issue is that after a cleanup the first callback is not called (if the corresponding action is the first after cleanup), for instance suppose we have a simple callback on Document:
 * cleanup and view a document (beforeFind/afterFind are not called), view it again -> callbacks are called
 *  cleanup and do some other thing, then view document -> callbacks are called

we could live with that, not a big deal, @fquffio can you just have a look to make sure it's not a bug somehow?
then we may close/merge

**Comment by fquffio** [comment]
@stefanorosanelli This is due to the fact that right after a cleanup we happen to have empty `objectTypes` key in configuration (because model is first loaded during the process of caching configuration itself), so `CallbackBehavior` doesn't recognize `Document` to be a valid BEObject and it doesn't attach anything to it. I guess this was also the main cause of the issue found by @batopa.

This should have been fixed by performing a flush of `ClassRegistry` after caching configuration.

**Comment by batopa** [comment]
@fquffio doing some tests and all seems work properly. Good job! Closing
