### ISSUE TITLE
admin: software update from git/svn

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#485]
Implement in backend, new page __admin / software update__ the same logc and flow in ```DeployShell::up()```

Show feedback to user if update ok, error message on failure

See also #217 
Maybe @edoardocavazza could do something here?

**Comment by edoardocavazza** [comment]
@stefanorosanelli may you help me to find out why Travis fails the tests please?

After that, I think that we are ready for the testing.

I have introduced 3 new models:
- Git: a model that implements the R(evision)C(ontrol)S(ystem) interface, for git repository handling
- Svn: a model that implements the RCS interface, for svn repository handling
- Revision: an helper model that uses `Git` and `Svn` models in order to retrieve repository information

At the moment, I have not implemented those models in the deploy shell script. Maybe @batopa could help me for this in a separate issue?

**Comment by edoardocavazza** [comment]
moved to another branch `issue/485-software-update-2`, too much problems with merging `3-corylus` into the old one. Now Travis validation is ok. 

Now the [test instance](http://test.bedita.net/) points to `issue/485-software-update-2`

**Comment by stefanorosanelli** [comment]
Seems ok, good job!
The only problem left is user message with update details and general git/svn output - current message box is not working for that: small display box, disappears quickly
do we have to wait for #644 ? 
or we could use a custom modal or in page ajax div

**Comment by edoardocavazza** [comment]
Maybe we could just prevent the auto fade out in this case, without wait for #644

**Comment by stefanorosanelli** [comment]
OK, let's do that, so we can close this

**Comment by edoardocavazza** [comment]
Done! Now the view is dynamically updated with new commit data too.

**Comment by stefanorosanelli** [comment]
ok! please merge it to 3-corylus
you can close the issue after merge

minor enhancements (news issues):
 * add link to git web interface (github, gitlab...)
 * refresh git info after ajax update - now we are seeing previous info

**Comment by edoardocavazza** [comment]
merged.

- ```refresh git info after ajax update - now we are seeing previous info``` 

it should already work.

- ```add link to git web interface (github, gitlab...)``` 

do you mean a generic link for the repository or the link to the last commit?

**Comment by stefanorosanelli** [comment]
Link to repository and branch or single commit would be nice... maybe we could add some info to .git/config ?

After update I see previous values for __Last commit: .. - on date: ... - by: .... __ refreshing the admin page I get new ones. We could live with that....

**Comment by stefanorosanelli** [comment]
Closing
Will (maybe) open new issues from my previous comment
