### ISSUE TITLE
Publications: review detail page

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#504]
We should be able to see contents, sections and properties of a section at the same time like in other objects detail views.

**Comment by qwerg** [comment]
@stefanorosanelli take a look!

**Comment by stefanorosanelli** [comment]
Seems ok.
Is there a pagination? In case of many contents/sections...
@xho have a look.. (branch: issue/504-publications-review-detail-page)

**Comment by qwerg** [comment]
Only "contents" are paginated.

**Comment by stefanorosanelli** [comment]
Seems good!
A useful additional filter could be: see only sections or only publications
As label above filter, instead of __areas__ we should have __publications, sections__

@batopa what do you think?

**Comment by batopa** [comment]
It is much better then before. Some consideration:
- controller  and some views need refactoring. Now `AreasController::index()` redirect to `AreasController::results()` if no _id_ was passed otherwise it calls `AreasController::view($id)`. Moreover  `AreasController::results()` filter only _sections_ so the list you see entering in Publications is a list of sections. Is it wanted? I suppose that module index should show a list of all publications and sections.
- To add filter for publications or sections is very simple, it's already used for example in Multimedia module. All you need to do is:
  - activate the filter 'type'
  
  ```
  {$view->element('filters', [
         'options' => ['type' => true]
  ])}
  ```
  - assure to have set $objectTypeIds as array of object type ids to show

**Comment by qwerg** [comment]
Refactor of controller is needed, but I have preferred to release quickly a stable version and proceed with a deep refactor later. (this involves also tree, different behaviour of index/id, etc).
For the same reason I'have preferred to handle in list (and in bulk operations!) only sections and not publications.

**Comment by qwerg** [comment]
Results page now manage both areas and sections, but without bulk delete button

**Comment by stefanorosanelli** [comment]
branch **issue/504-publications-review-detail-page** merged to **3-corylus** and removed

@batopa do we keep this issue or open a new one for refactoring ?

**Comment by batopa** [comment]
Keep open. I'll give a look at soon as possible.

**Comment by xho** [comment]
@qwerg 
This insertion in list_objects_bulk causes problems to all custom list_objects that include it
`{if isset($bulk_delete) && $bulk_delete==true}`

For example now in module Addressbook the “delete selected” button is not available.
This way we have to change also all the plugins deployed that have a custom list_objects template.

It should have been the opposite, a condition like:
`{if !isset($hide_bulk_delete) || $hide_bulk_delete==false}`

and where required to hide set 
`hide_bulk_delete = true`

**Comment by qwerg** [comment]
ok
