### ISSUE TITLE
frontend: use hreflang and different urls for content translations

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#517]
https://support.google.com/webmasters/answer/189077?hl=en#
- use tag links in HTML header to mark all traslations available (current page also)  
  `<link rel="alternate" hreflang="es" href="http://es.example.com/" />`
- use different urls for different contents translations/versions

Now we use /lang/xxx at the beginning of urls to change session language and redirect to content, for example using www.example.com/lang/spa/my-content causes:
- change to 'spa' spanish as session language
- redirect to  www.example.com/my-content/ using spanish as language

We should have something like:
- www.example.com/lang/spa/my-content/ that points to the spanish version
- english (or default language) version may be at www.example.com/lang/eng/my-content/ or www.example.com/my-content/
- current behaviour (redirect) stays default in backend
- in frontend we can activate redirect via config parameter
- urls in frontend pages should be in the same (current) language, if available, like  www.example.com/lang/spa/another.content/

**Comment by fquffio** [comment]
Most of the work should have been done by now.
`FrontendController` now handles correctly the `lang` parameter in URLs switching from a language to another.
Language persistence in URL cannot be achieved in an easy way, though. Many of the links in frontends are built the "wrong" way:
```html
<a href="{$html->url('/my_controller/my_action/my_other_param')}">Lorem ipsum</a>
<!-- Instead of the more standard and more stable alternative: -->
<a href="{$html->url(['controller' => 'my_controller', 'action' => 'my_action', 'my_other_param'])}">Lorem ipsum</a>
```
Because of this, we cannot simply prepend `'/lang/xyz'` to all URLs, as it may introduce unexpected behaviors. Hence, it has been introduced a new `BeHtmlHelper` that parses the passed URL using the configured routes, adds the `lang` parameter, and then rebuilds the whole URL passing it back to the `Router` class in the array form. It might look a bit tricky, but it's the best ("cleaner" & simpler) I could figure out by now.
Of course, this needs a soft frontend conversion. A working example would be fquffio/bootstrap@9bfb99cd7ba80e643c65fd55799ae9ec89ffc6ed.

To do:
- [ ] Address and fix an issue with named parameters (that by the way are not massively used in frontends, as far as I know).
- [ ] Add `<meta rel="alternate" />` tags in `<head>` section (this will probably need an additional parameter passed to view, as it would be possible to figure it out only when a single object is displayed).

@stefanorosanelli @batopa @edoardocavazza @qwerg Any critics and/or better solutions? :smile:

**Comment by stefanorosanelli** [comment]
Just to clarify: we normally have

```<a href="{$html->url('/some/path')}">....</a>```

that may produce something like

```<a href="/some/path">....</a>```

Instead, using

```<a href="{$beHtml->url('/some/path')}">....</a>```

Will output, if we're using 'spa' as language

```<a href="/lang/spa/some/path">....</a>```

Correct?

**Comment by fquffio** [comment]
@stefanorosanelli Yes.

**Comment by stefanorosanelli** [comment]
I've seen the example in your bootstrap frontend, can you merge it in into bedita/bootstrap so we can test it?
A couple of questions:
 * is the new routing rule in ```config/routes.php ```necessary?
 * in case of single-language frontends does ```$beHtml->url()``` return same urls as ```$html->url()``` ?

**Comment by fquffio** [comment]
@stefanorosanelli I'll push the example to bedita/bootstrap shortly. In the meanwhile, to answer your questions:
- it **is not** necessary in order to change language, but it **is** necessary to obtain consistency in internal links. In other words, without that routing rule, visiting http://www.my-be-site.com/lang/fra/mypage would display the requested page in French without redirection, but that page would link to http://www.my-be-site.com/myotherpage without language token persistence in URL, and the new `BeHtmlHelper` would act exactly as `HtmlHelper`. As I wrote above, we could obtain URL persistence in a more brutal way that does not involve additional routing rules, but this might carry some issues with external static resources.
- yes.

**Comment by edoardocavazza** [comment]
up!!!!

**Comment by stefanorosanelli** [comment]
I know, I know....

**Comment by stefanorosanelli** [comment]
Did some tests (finally!!) on a simple frontend with **eng/ita** languages having **eng** as default `frontendLang` using bootstrap dedicated branch:
-  defaullt links are `/lang/eng/...`  OK - but can we keep the (current) standard canonical path links for default language or do we have to use `/lang/xxx/` prefix always also for default language?
- link tags seem ok - always using `/lang/xxx/` prefix
- switching language with `/lang/ita/` content is correctly translated, session `Config.language` is `ita`, lang cookie is `ita` but  `$beHtml->url()` links are still using `/lang/eng/...`

**Comment by fquffio** [comment]
@stefanorosanelli Sorry for delay. Should be ok now: first point should have been satisfied (but requires a further minor change in frontends, as `BeHtml` helper needs to be **explicitely** instantiated by frontend's `PagesController` with an empty array of options **before** `BeFront` helper), while third point has been fixed.

**Comment by stefanorosanelli** [comment]
tested again - everything seems ok now
merged to 3-corylus

we need to document it before closing
@fquffio I think we could reuse what you wrote in this issue and in pull request https://github.com/bedita/bedita/pull/616 

@batopa where? wiki? docs.bedita.com?

**Comment by fquffio** [comment]
Fine. Thanks for testing. :smiley: Tell me where docs should be placed, and I'll take care of it ASAP.

**Comment by stefanorosanelli** [comment]
Doc is online
http://docs.bedita.com/frontends/url-friendly-content-translations
Closing
