### ISSUE TITLE
Remove "fixed" property

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#588]
The last user that edited a "fixed" object (adding the ```fixed``` flag), should be able to remove that property. At the moment, nobody (admins neither) can change the flag.

**Comment by fquffio** [comment]
It should be enough to put
```html
<input type="hidden" name="data[fixed]" value="0" />
```
...just before
```html
<input type="checkbox" name="data[fixed]" value="1" />
```

This way, the `fixed` key is always present in the `$this->data` array, therefore such field could not be ignored by the `BEObject::save()` method.

I could take care of this, but I don't know if this is an intentional behavior. @batopa @stefanorosanelli ?

**Comment by stefanorosanelli** [comment]
No, it's not an intentional behavior.
If fixed is checked we should be able to remove **fixed** and return to _normal_ status display

Also: if **fixed** is checked it would be nice to see current (unmodifiable) state - now we can't see it.

**Comment by fquffio** [comment]
This should be ok, now. It is needed to update every BEdita plugin module that overwrites `form_property.tpl`, as well.

Anyway, we have #590 now.

**Comment by stefanorosanelli** [comment]
Ok, closing
