### ISSUE TITLE
data XML import/export based on JSON

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#606]
Implement the XML equivalent of the JSON import / export as seen in #561 and https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects

**Comment by fquffio** [comment]
@stefanorosanelli @didoda Should be fine and working. I've added a `XmlJsonConverter` business model that tries to obtain an array representation of a well-formed XML tree and vice versa. This uses a slightly different format from the one seen in [this draft](https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects#xml-example), and I will update that document soon, so that you can tell me what's wrong with new proposal. :wink:

We might also try to make `XmlJsonConverter` a bit more configurable, so that it can handle more specialized array-to-xml-forth-and-back conversions, even if current version should be already enough flexible.

**Comment by stefanorosanelli** [comment]
XML draft format seems OK
XmlJsonConverter could go in libs instead of models?

Did some testing on a publication with many documents, images and so on...
Export seems ok - in import relations are not handled correctly - no relation was imported

I may provide an example to use if necessary

**Comment by stefanorosanelli** [comment]
Ok. Merged to 3-corylus
Please remove issue branch.
