### ISSUE TITLE
xss vulnerability 

### ISSUE THREAD

**Issue by ankitbharathan** [bedita/bedita#610]
http://manage.demo.bedita.com/documents/index/id:%22%3E%3Cimg%20src=d%20onerror=confirm%281%29;%3E

![screenshot_5](https://cloud.githubusercontent.com/assets/3707662/6465787/3feec5f2-c1e9-11e4-899e-271a33f5d63e.png)

**Comment by ankitbharathan** [comment]
issue is expoitable without login also refer screenshot 

![screenshot_6](https://cloud.githubusercontent.com/assets/3707662/6465859/c02ca5b8-c1e9-11e4-9fd2-c4003be00fb4.png)

**Comment by fquffio** [comment]
@ankitbharathan Thank you for reporting this issue! We're working on it.

Issue seem to affect only Firefox. On Chrome there are some visual glitches, but no malicious JS execution.

**Comment by ankitbharathan** [comment]
Chrome has a xss filter thats why it dont let javascript execute you can
simply disable xss filter on chrome and try again

**Comment by fquffio** [comment]
I had to escape also `menucommands.tpl` because, if accessing to the URL in OP, then navigating towards "Create new document", the malicious code did display as the "back" URL in the left menu. This issue did affect other modules apart from Documents as well, but should be fixed everywhere by now. Also plugin modules (Tickets, Books and Glossary) should be OK.

@batopa @stefanorosanelli

**Comment by batopa** [comment]
@fquffio ok, I'll have a look as soon as possible, anyway looking the commit it seems right

**Comment by fquffio** [comment]
@batopa Fix'd vulnerability also on ordering fields.
