### ISSUE TITLE
backend: id/nickname direct lookup

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#611]
Easy direct access to a specific object by id/nickname
Currently only possibile changing url manually to: **/view/[id]** or **/view/[nickname]**

May we use the search box?
Another search input?

**Comment by xho** [comment]
I did a version. We may change position and icon of the button: now in the top modules menu on the right, next to search.

**Comment by qwerg** [comment]
Can we include it directly in the search form Field?
maybe with an #

**Comment by stefanorosanelli** [comment]
Changed label: _unique name_ instead of _nickname_
@qwerg: I think the action here is different: it's a **go to**, not a **search for** - but you may change UI...

**Comment by stefanorosanelli** [comment]
Reopen issue, if we use this lookup from a plugin module we get this error
__Security error: CSRF token is invalid. Please try to resubmit the form__ and lookup doesn't work

Frome a core module everything is ok

@batopa is there a quick fix for this?

**Comment by stefanorosanelli** [comment]
see #597 #602

**Comment by batopa** [comment]
It's a bit complicated. We should upgrade all plugin modules to handle CSRF token.

We could work around the issue in two ways:

1. move that function in ModuleController instead of PagesController so only modules that are protected against CSRF will receive the error if some attacks happens. Pay attention that plugin modules that have no `BeSecurity` component enabled will be exposed to CSRF attacks.
2. transform the POST request in a GET request
