### ISSUE TITLE
admin / system info - check requirements

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#635]
In __system info__ display a warning message if some of the requirements are not met:
http://www.bedita.com/documentation/requirements

Tyipically missing php modules or other 3rd party versions mismatch

**Comment by stefanorosanelli** [comment]
It's ok
Maybe we could load requirements.php only in admin/systemInfo

**Comment by edoardocavazza** [comment]
Maybe, we should add a warning level to each one requirement. The PHP version is a blocker requirement, as well as DB versions. `gettext` extension is not a blocker feature instead. Also, we could stop the app if the minimum requirements are not satisfied (in setup too), and leave the warnings in admin/systemInfo.

What do you think about this? @stefanorosanelli  @fquffio

**Comment by fquffio** [comment]
@edoardocavazza In case PHP major/minor version is too old, it occurs a fatal error in pre-compile phase, as PHP syntax has significantly changed across minor versions of PHP 5 (terms as of [Semantic Versioning](http://semver.org)), and plenty of backwards-incompatibilities have been introduced even if this wasn't really supposed to happen. If we actually want to add a helpful warning for users running an outdated PHP major/minor version, we should consider adding that warning to `webroot/index.php`, written in pure PHP, even before including `config/bootstrap.php` or whatsoever.

Database checking, on the other hand, should happen after CakePHP has established connection to the server, to avoid repeating the code, but it should be executed on every script execution, and I'm not sure whether this is an application-wide blocking feature, as CakePHP's ORM tries to use as much "pure SQL" as it can, so it could be a bit exaggerated to block the whole thing because of that.

**Comment by stefanorosanelli** [comment]
@fquffio I would not handle cases where PHP version is too old... what you suggest is correct, but users should have a look at real requirements and I don't want to handle any possible situation...for "close" minor versions this warning may help

To summarize and simplify @edoardocavazza proposal: display as error (and not simple warning) any DB/PHP issue, keep warning for PHP modules.

Also current implementation is ok for me, @fquffio you decide :)

**Comment by stefanorosanelli** [comment]
@fquffio you can close it ... or are you still working on it?
