### ISSUE TITLE
dynamic callbacks not working for some object types

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#688]
dynamic callbacks introduced in #470 seem not to trigger method calls for some object types:
document, event and card are ok, but image, video not
also some plugin models seem to work (like tickets) other no

**Comment by stefanorosanelli** [comment]
seems ok now, tested on some object types like image, video and other plugin models
is it necessary to test **every** object type?

**Comment by batopa** [comment]
The issue was the lacking of `Callback` behavior on some object type due to the 'strange' way CakePHP 1.3 merges the `$actsAs` property.

I added some assertions in unit test in `generic_object.test.php` in the method `testActsAs()`

``` php
$isIn = in_array('Callback', $model->actsAs);
$this->assertTrue($isIn);
$this->assertTrue($model->Behaviors->attached('Callback'));
$this->assertTrue($model->Behaviors->enabled('Callback'));
```

executed for every core object types. I think it is enough. Plugged object types are not covered but they should be extend a base class used also from core object types.

**Comment by stefanorosanelli** [comment]
Ok seems enough, closing
