### ISSUE TITLE
Concurrent save of a model generates an insert error

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#752]
A concurrent save of a model can generate the same nickname hence an INSERT error in the database (due to it's uniqueness requirement)

**Comment by didoda** [comment]
Nickname generation (or model->save?) should be managed through a concurrent controlling access system (binary semaphore? mutex?). 
For instance: 2 models try to acquire nickname concurrently. Only one of the two models acquire the nickname-semaphore (and lock it in db); when nickname creation is done (model has been saved), model release the nickname-semaphore (change value of semaphore in db). As long as semaphore in db is lock, model saves wait.
I assume we can't use php semaphores, because bedita could be installed in a distributed system (multi server).

Important avoiding deadlocks and starvation. This approach could be dangerous.

**Comment by stefanorosanelli** [comment]
still an interesting topic - let's find a solution in BE4

**Comment by fquffio** [comment]
See #1049.
