### ISSUE TITLE
Missing PHP 7 support

### ISSUE THREAD

**Issue by GitGianluc** [bedita/bedita#778]
bEdita is expected to meet the new PHP 7 requirements, as for – I guess – the MySQL connection parameters. Using PHP 7 currently causes a 500 error.

**Comment by stefanorosanelli** [comment]
Hi @GitGianluc BEdita 3.7 does not support PHP7 right now, but we are going to look into it and try to make it work.
Do you have any error logs from BEdita or Apache/Mysql? Could be useful.

**Comment by GitGianluc** [comment]
This is the only odd message (php_error.log):

`[22-Dec-2015 10:32:28 Europe/Berlin] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /Applications/MAMP/htdocs/bedita/cake/libs/inflector.php on line 303`

but I'm not sure whether it is related to the problem which we are talking about.

**Comment by fquffio** [comment]
@GitGianluc Yes, it definitely is. There are several code incompatibilities in the Cake library itself, such as `$instance[0] =& $someObject` (the error you refer to). This was a fairly common practice back in the days of PHP 4, but has been deprecated as soon as PHP 5 arrived, and then removed in version 7.

Once solved this problem (160+ files modified!), there still are some issues popping up, such as the compiler blaming about the CakePHP class `String`, that uses a newly-introduced reserved word. I'm working on it…

**Comment by GitGianluc** [comment]
@fquffio OK, let's get in touch! Thank you and good luck with your work.

**Comment by fquffio** [comment]
Ok, I'm afraid it's gonna be quite a series of mastodontic commits. We have tons of warnings and incompatibilities coming from vendor libraries… :disappointed:

In order to fix syntax errors only, I had to edit 285 files. There are still loads of method declarations that are not compatible with their parent class' ones. I'm creating a separate branch, but it's gonna be long and painful. :scream:

Moreover, I'm afraid we'll have to accept that some warnings just won't go away: there are some (luckily few) cases where a child class method overrides a parent's one "by chance", thus making the method signatures compatible with each other is impossible, and the only option would be renaming the child class method.
This happens, for instance, with `BeEmbedMediaHelper::object()` overriding `Object::Object()` (PHP4-style constructor): we should rename the `object()` method in `BeEmbedMediaHelper`, but we can't as it might break some frontend… :unamused:

**Comment by batopa** [comment]
I think that BE3.x could not support PHP 7. I don't like the idea of modify so many vendor libraries and cake too.
BE4 will support it natively.

@stefanorosanelli  @fquffio do we really need to support PHP7 in 3.x series? What do you think?

**Comment by fquffio** [comment]
@batopa Actually, I think it could be skipped as well, and I'm not keen in modifying vendors too. On the other hand, are we actually updating those libraries? The only point in leaving dependencies _as is_ is to provide updates with ease. In our case, fixes are always very trivial, and in most cases the library versions we use are discontinued or abandoned, so I think we could feel free to edit them as we like. :smile:

Of course, with BE4, dependencies will be managed via Composer, so this won't be possible any more, but that's another story. :wink:

**Comment by stefanorosanelli** [comment]
Even if changes are trivial, there are too many - we could introduce some subtle errors, agree with @batopa: I don't like it

BE3 series have to remain stable for some time - we will fix bugs but we could live without PHP 7 support

Another good reason to accelerate on BE4 development :)

**Comment by fquffio** [comment]
Alright, then… :smile: Should we shift this to the `4-release` milestone, or add the `Wontfix` label?

By the way, while working on this, I found out a few things that could be ported to the `3-corylus` branch. To be specific:
- TravisCI tests are running on PHP 5.3 and 5.4 only: should we cover 5.5 and 5.6 too?
- We are still using `mysql` PHP drivers as the default value in `database.php.sample` (and possibly in many BEdita instances across the globe), but `mysql` extension has been deprecated in PHP 5.5 and `mysqli` is recommended to take its place. However, setting drivers to `mysqli` leads to some issues: should we implement compatibility out-of-the box?

**Comment by batopa** [comment]
I will close with `Wontfix` status. And :+1: for adding tests on 5.5 and 5.6.
About `mysqli` driver. What issues are?

**Comment by fquffio** [comment]
@batopa Well, for instance `./cake.sh bedita initDb` attempts to read schema from a non-existing `config/sql/bedita_mysqli_schema.sql`. There are also some missing methods and array keys in `BeSystem` and things like that. I wasn't able to solve all problems, yet: I was still debugging. Issues were apparently only in BEdita (not vendors), and I think it should be pretty easy to get things working.

**Comment by stefanorosanelli** [comment]
:+1: for adding 5.5 and 5.6 in TravisCI

:+1: to support `mysqli` driver - new issue?

**Comment by fquffio** [comment]
@stefanorosanelli Yep, maybe another issue would be better.

**Comment by fquffio** [comment]
@batopa @stefanorosanelli Shall we mark this issue as "wontfix" and close it?

**Comment by stefanorosanelli** [comment]
yes :+1: 
Travis support for 5.5 and 5.6 has been added?

**Comment by fquffio** [comment]
@stefanorosanelli Yes, in #797

**Comment by clifordmlotshwa** [comment]
Does BEdita 3.8 support PHP7

**Comment by fquffio** [comment]
@clifordmlotshwa No, sorry. :( With PHP 7, a number of issues arise, mainly syntactical rules like the `=&` operator that does not exist anymore, and #798. Since many of these issues come from our vendors, this would have required a massive update of legacy code it wasn't even us to write. :)

To sum up, as far as I can remember we decided to not provide support for PHP 7 until BEdita 4, which is currently being developed.

**Comment by clifordmlotshwa** [comment]
Ok, Thanks!
