### ISSUE TITLE
Events: cannot create dates from backend with php 5.3

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#834]
After #670 we have some problems with PHP 5.3

Saving calendar dates from backend is not working anymore - dates are _0000-00-00 00:00:00_ on DB

**Comment by stefanorosanelli** [comment]
in `models/date_item.php` it works after substituting these lines in `prepareDate` 

``` php
           $date = preg_replace('/^-|([\/-])-/', '$1', $date, -1, $negative);

           $pattern = str_replace('%', '', Configure::read('datePattern'));
           if (($dateTime = date_create_from_format($pattern . ' G:i|', $date)) || ($dateTime = date_create_from_format($pattern . '|', $date))) {
               $date = date_format($dateTime, 'Y-m-d H:i:s');
           }

           if ($negative) {
               $date = '-' . $date;
           }
```

with these:

``` php
            $time = strlen($date) > 10 ? ' ' . substr($date, 11) : '';
            $date = $this->getDefaultDateFormat(substr($date, 0, 10)) . $time;
```

**Comment by fquffio** [comment]
The substitution you suggested wouldn't work for b.C. dates, nor for years after 9999 A.D.

I still haven't looked in depth, but honestly I doubt this is related to PHP version.
- `preg_replace`'s `$count` parameter (here `$negative`) has been introduced in 5.1
- `date_format` has been introduced in 5.2
- `date_create_from_format` has been introduced in 5.3, with further additions (not used in this snippet) in 5.3.9

Other constructs and functions have been there since PHP 4. Hence, I'm more keen in thinking that this is due to a misconfiguration. To be specific, I'd like to know how `$configure['datePattern']` looks like, as I feel its likely to be its fault.

**Comment by qwerg** [comment]
On the problematic server, (PHP 5.3.3 / MySQL: 5.1.73)
in _bedita.ini_ we have:

``` php
/* Dates - default presentation format [syntax used by strftime php function]
 * It is used for datepicker calendar. Format has to contain %d,%m,%Y tags
 */
$config['datePattern']  = "%m-%d-%Y" ;
/* Date patterns for different locales
 * It is used for datepicker calendar. Format has to contain %d,%m,%Y tags
 */
$config['datePatternLocale'] = array(
    "ita"   => "%d/%m/%Y"
);
// Default date time pattern
$config['dateTimePattern']  = "%m-%d-%Y  %H:%M";  //
$config['dateTimePatternLocale'] = array(
    "ita"   => "%d/%m/%Y %H:%M"
);
```

no ovverides in _bedita.cfg.php_

**Comment by stefanorosanelli** [comment]
@fquffio I know that the patch is not working in those cases, even more probably... but it does work for a project using recent/current dates - so it's temporary of course and not my solution proposal

**Comment by fquffio** [comment]
The issue is with the `|` modifier, which was apparently introduced in 5.3.7, even though this is not documented in the PHP docs: http://php.net/manual/en/datetime.createfromformat.php#107452
