### ISSUE TITLE
Refactor relation between users and profiles tables

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#931]
In order to remove ambiguities in user model between object and non object part use table inheritance to define user data.
New relation will be: users table extend profiles table that extends objects table

```
objects  -->  profiles  -->  users
```

Relations between users and roles table remain unchanged.

**Comment by stefanorosanelli** [comment]
First schema proposal committed:
- `users` table extends `objects` - actually `profiles` and `objects`
- `objects.created_by` and `objects.modified_by` are created as simple UNSIGNED INT NOT NULL then: first record in `users` is inserted (non removable administrator), right after the expected constraint for `objects.created_by` and `objects.modified_by` is set

There are some SQL inserts in schema file: that's far from optimal, but the quickest solution found.
Other minimal data-set through inserts, like admin role and core object_types, will go in a separate SQL file.

I did not change schema JSON otherwise all tests will fail.
After #873 we may apply code changes to pass all tests.

**Comment by fquffio** [comment]
Right now, tests are still failing. The failure, though, is due to an issue when deleting an entity in a table that extends another table using CTI (see #948).

@stefanorosanelli @batopa @didoda What should we do? Should I open a PR against `4-develop` while we wait for #948 to be solved, even if this would cause all builds to fail in the meanwhile? Should we temporarily disable the failing test?

(BTW, what I did in b172713 is a bit weird, because `ORDER BY id ASC` is usually implicit, but I could not find any reasonable explanation for [this failure](https://travis-ci.org/bedita/bedita/jobs/155391478#L371-L458)… Anybody has a plausible one?)

**Comment by stefanorosanelli** [comment]
depends on #948: if it's not difficult to solve I would first try to fix that - maybe you - @fquffio - could help @batopa or auto assign it

estimate is 5 so i guess it's not too trivial

if #948 takes too much time I would disable failing tests, adding a note in #948 to re-enable and check those failing tests when issue is solved

**Comment by batopa** [comment]
PR #970 merged. Closing
